# Generated by Django 5.2.1 on 2025-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('track', models.CharField(choices=[('hr', 'HR Interview'), ('tech', 'Technical Interview')], default='hr', max_length=16)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('qa', models.JSONField(blank=True, null=True)),
                ('evaluation', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
