# Generated by Django 5.2.1 on 2025-11-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('results', models.JSONField()),
                ('raw_answers', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
