# Generated by Django 5.2.1 on 2025-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('raw_session', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='career_resumes/')),
            ],
        ),
    ]
